### ISSUE TITLE
getting the name of the file inside the .zip archive

### ISSUE THREAD

**Issue by Kr1ss-XD** [ABOg4Ti/Tryhackme-Carnage-writeup#1]
Hi, first of all thank you for this wonderful writeup. I was needing a hint as to how to get the Cobalt Strike IPs, and I'm happy that I've found this.

As to the answer for question 4, you asked for some advice on how to find the file name without downloading the archive. Well, how I did it was right-clicking the packet with the request GETting `documents.zip` (i.e. request `#1735`), and to `follow` -> `http stream`. Then, in the first few bytes of the first response packet, I was able to spot a name ending in `.xls`, which had to be it. :smile:

_Cheers !_

**Comment by ABOg4Ti** [comment]
I'm very happy to know that my writeups was useful for you. And i really
thank you for the hint.

have a good day.
